import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import '@/styles/globals.css'
import '@/styles/layout.css'
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster"
const fontSans = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "AICODEX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body   className={`${fontSans.className} min-h-full dark`}>
   
            
        {children}
        <Toaster />
  
      </body>
    </html>
  );
}
